# Generated by Django 3.0.3 on 2020-08-17 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='photo_0',
        ),
    ]
